import { useState } from 'react'
import type { FormEvent } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronLeft, Eye, EyeOff, Headphones, LockKeyhole, ShieldCheck, Sparkles, UserRound, Wrench } from 'lucide-react'
import { login, register } from './api/authApi'
import type { UserRole } from './types/auth'
import './App.css'

const roleCopy: Record<UserRole, { label: string; title: string; description: string; icon: typeof UserRound }> = {
  customer: { label: 'Customer', title: 'Welcome back', description: 'Manage your devices, troubleshoot problems, and track service requests.', icon: UserRound },
  electrician: { label: 'Technician', title: 'Technician Portal', description: 'Manage assigned jobs, service requests, and your technician profile.', icon: Wrench },
  admin: { label: 'Admin', title: 'Admin Portal', description: 'Manage users, technician verification, and platform operations.', icon: ShieldCheck },
}

function App() {
  return <BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route path="/admin/login" element={<Login />} /><Route path="/register/:role" element={<Registration />} /><Route path="/verify/:role" element={<StatusPage />} /><Route path="/technician/verification" element={<StatusPage />} /><Route path="/electrician/verification" element={<StatusPage />} /><Route path="/forgot-password" element={<UtilityPage />} /><Route path="/reset-password" element={<UtilityPage reset />} /><Route path="/customer/dashboard" element={<DashboardPlaceholder />} /><Route path="/technician/dashboard" element={<DashboardPlaceholder />} /><Route path="/electrician/dashboard" element={<DashboardPlaceholder />} /><Route path="/admin/dashboard" element={<DashboardPlaceholder />} /><Route path="*" element={<Navigate to="/login" replace />} /></Routes></BrowserRouter>
}

function Shell({ children, back = false }: { children: React.ReactNode; back?: boolean }) {
  return <div className="portal"><header className="topbar"><Link className="brand" to="/login"><span className="brand-mark"><Sparkles size={18} /></span><span><strong>SmartAssist AI</strong><small>Smart Home Support Platform</small></span></Link>{back ? <Link className="back-link" to="/login"><ChevronLeft size={16} /> Back to login</Link> : <button className="support-link" type="button"><Headphones size={16} /> Help / Support</button>}</header>{children}<footer className="page-footer">© 2026 SmartAssist AI <span>•</span> Support for every connected home</footer></div>
}

function Login() {
  const location = useLocation(); const navigate = useNavigate(); const initialRole = location.pathname.startsWith('/admin') ? 'admin' : 'customer'
  const [role, setRole] = useState<UserRole>(initialRole); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const copy = roleCopy[role]
  const chooseRole = (nextRole: UserRole) => { setRole(nextRole); setMessage(''); navigate(nextRole === 'admin' ? '/admin/login' : '/login') }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!identifier || !password) return setMessage('Enter your email or mobile number and password.'); setBusy(true); setMessage(''); const result = await login(role, identifier, password); setBusy(false); navigate(result.role === 'electrician' ? '/technician/verification' : `/${result.role}/dashboard`) }
  return <Shell><main className="auth-layout"><section className="intro-panel"><div className="eyebrow"><span className="pulse-dot" /> SMART HOME SUPPORT</div><h1>Diagnose smarter.<br /><em>Get help faster.</em></h1><p>One calm place to troubleshoot devices, connect with trusted technicians, and keep your home running beautifully.</p><div className="intro-notes"><div><LockKeyhole size={18} /><span><strong>Private by design</strong><small>Your account and service details stay protected.</small></span></div><div><ShieldCheck size={18} /><span><strong>Human help when it matters</strong><small>Escalate from AI guidance to verified professionals.</small></span></div></div></section><section className="auth-card"><div className="mobile-brand"><span className="brand-mark"><Sparkles size={18} /></span> SmartAssist AI</div><div className="card-heading"><span className="role-icon"><copy.icon size={21} /></span><div><h2>{copy.title} {role === 'customer' && <span aria-hidden="true">👋</span>}</h2><p>{copy.description}</p></div></div><RoleSelector role={role} onChange={chooseRole} /><form onSubmit={submit} className="auth-form"><Field label="Email or Mobile Number" value={identifier} onChange={setIdentifier} placeholder="you@example.com" autoComplete="username" /><div className="field"><label htmlFor="password">Password</label><div className="password-wrap"><input id="password" type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" /><button className="icon-button" type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div>{message && <p className="form-message" role="alert">{message}</p>}<div className="form-actions"><Link to="/forgot-password">Forgot password?</Link></div><button className="primary-button" type="submit" disabled={busy}>{busy ? 'Signing in...' : 'Login'} {!busy && <ArrowRight size={17} />}</button></form>{role !== 'admin' ? <div className="register-prompt"><span>{role === 'customer' ? "Don't have an account?" : 'New to SmartAssist?'}</span><Link to={`/register/${role === 'electrician' ? 'technician' : role}`}>{role === 'customer' ? 'Create Customer Account' : 'Register as Technician'}</Link>{role === 'electrician' && <small>Professional verification is required before service assignments.</small>}</div> : <div className="admin-note"><LockKeyhole size={16} /> Authorized administrators only. <span>No public registration.</span></div>}<div className="card-footer"><span><span className="footer-dot" /> Mock development mode</span><span>Secure access</span></div></section></main></Shell>
}

function RoleSelector({ role, onChange }: { role: UserRole; onChange: (role: UserRole) => void }) { return <div className="role-control" role="tablist" aria-label="Login as">{(['customer', 'electrician', 'admin'] as UserRole[]).map((item) => <button key={item} type="button" role="tab" aria-selected={role === item} className={role === item ? 'selected' : ''} onClick={() => onChange(item)}>{roleCopy[item].label}</button>)}</div> }

function Field({ label, value, onChange, placeholder, autoComplete, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; autoComplete?: string; type?: string; required?: boolean }) { const id = label.toLowerCase().replaceAll(' ', '-'); return <div className="field"><label htmlFor={id}>{label}{required && ' *'}</label><input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} autoComplete={autoComplete} required={required} /></div> }

function Registration() {
  const { role = 'customer' } = useParams<{ role: 'customer' | 'electrician' }>()
  const navigate = useNavigate()
  const customer = role === 'customer'
  const steps = customer ? ['Account', 'Contact / Location', 'Preferences', 'Review', 'Verify'] : ['Account', 'Professional', 'Service Area', 'Review']
  const [step, setStep] = useState(1)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [data, setData] = useState<Record<string, string>>({})
  const update = (key: string) => (value: string) => setData((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => {
    event.preventDefault()
    if (step === 1 && (!data.name || !data.email || !data.mobile || !data.password || !data.confirmPassword)) return setError('Please complete all required account fields.')
    if (step === 1 && data.password !== data.confirmPassword) return setError('Passwords do not match.')
    setError('')
    if (step < steps.length) return setStep(step + 1)
    setBusy(true); await register(role); setBusy(false)
    navigate(customer ? '/verify/customer' : '/technician/verification')
  }
  const field = (label: string, key: string, placeholder: string, type = 'text') => <Field label={label} value={data[key] ?? ''} onChange={update(key)} placeholder={placeholder} type={type} required />
  const renderStep = () => {
    if (step === 1) return <>{field('Full Name', 'name', 'Your full name')}{field('Email Address', 'email', 'you@example.com', 'email')}{field('Mobile Number', 'mobile', '+91 00000 00000', 'tel')}{field('Password', 'password', 'At least 8 characters', 'password')}{field('Confirm Password', 'confirmPassword', 'Repeat your password', 'password')}</>
    if (customer && step === 2) return <>{field('Address Line 1', 'address1', 'House number and street')}{field('Address Line 2', 'address2', 'Apartment, area (optional)')}{field('City', 'city', 'Your city')}{field('State', 'state', 'Your state')}{field('Pincode', 'pincode', '6-digit pincode', 'text')}{field('Landmark', 'landmark', 'Nearby landmark (optional)')}</>
    if (customer && step === 3) return <><fieldset className="choice-group"><legend>Preferred Language</legend>{[['en', 'English'], ['ta', 'தமிழ்'], ['te', 'తెలుగు']].map(([value, label]) => <label className="choice" key={value}><input type="radio" name="language" checked={data.language === value} onChange={() => update('language')(value)} />{label}</label>)}</fieldset><p className="field-help">We'll use this as the default language for your AI troubleshooting experience.</p><div className="upload-row"><span>Profile Photo <small>Optional</small></span><button className="secondary-button" type="button">Upload Photo</button></div></>
    if (customer && step === 4) return <div className="review-list"><Review label="Name" value={data.name} /><Review label="Email" value={data.email} /><Review label="Mobile" value={data.mobile} /><Review label="Service Location" value={`${data.city ?? ''}, ${data.state ?? ''}`} /><Review label="Language" value={data.language === 'ta' ? 'Tamil' : data.language === 'te' ? 'Telugu' : 'English'} /></div>
    if (!customer && step === 2) return <>{field('Years of Experience', 'experience', 'e.g. 8', 'number')}{field('Primary Specialization', 'specialization', 'Smart home systems, electrical...')}<fieldset className="choice-group"><legend>Service Categories</legend>{['Smart Home Devices', 'Security Cameras', 'Smart Lighting', 'Smart AC', 'Networking / Wi-Fi'].map((label) => <label className="choice" key={label}><input type="checkbox" />{label}</label>)}</fieldset><fieldset className="choice-group"><legend>Languages Spoken</legend>{[['en', 'English'], ['ta', 'Tamil'], ['te', 'Telugu']].map(([value, label]) => <label className="choice" key={value}><input type="checkbox" checked={data[`language-${value}`] === 'yes'} onChange={(event) => update(`language-${value}`)(event.target.checked ? 'yes' : '')} />{label}</label>)}</fieldset></>
    if (!customer && step === 3) return <>{field('Service City', 'city', 'Your city')}{field('State', 'state', 'Your state')}{field('Service Pincodes', 'pincodes', 'e.g. 600001, 600002')}{field('Service Radius', 'radius', '25 km') }<fieldset className="choice-group"><legend>Working Days</legend><div className="choice-grid">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day) => <label className="choice" key={day}><input type="checkbox" defaultChecked={day !== 'Saturday' && day !== 'Sunday'} />{day}</label>)}</div></fieldset><div className="time-row">{field('Start time', 'start', '09:00 AM')}{field('End time', 'end', '06:00 PM')}</div></>
    if (!customer && step === 4) return <div className="review-list"><Review label="Personal" value={`${data.name} · ${data.email} · ${data.mobile}`} /><Review label="Professional" value={`${data.experience || '—'} years · ${data.specialization || '—'}`} /><Review label="Service Area" value={`${data.city || '—'} · ${data.radius || '25 km'}`} /><Review label="Working Hours" value={`${data.start || '09:00 AM'} - ${data.end || '06:00 PM'}`} /></div>
    return <div className="placeholder-panel"><Check size={17} /><span>Account verification will be completed after submission.</span></div>
  }
  return <Shell back><main className="registration-layout"><div className="registration-copy"><div className="eyebrow"><span className="pulse-dot" /> {customer ? 'CUSTOMER ACCOUNT' : 'PROFESSIONAL ONBOARDING'}</div><h1>{customer ? <>Make your home<br /><em>easier to manage.</em></> : <>Put your expertise<br /><em>to work.</em></>}</h1><p>{customer ? 'Create your account in a few simple steps. You can add your devices after you are in.' : 'Build your professional profile. Approval follows the practical assessment and admin review.'}</p></div><section className="form-card"><div className="stepper">{steps.map((item, index) => <div key={item} className={index + 1 <= step ? 'step active' : 'step'}><span>{index + 1}</span><small>{item}</small></div>)}</div><p className="mobile-step">Step {step} of {steps.length}</p><h2>{steps[step - 1]}</h2><p className="form-subtitle">{customer ? 'Keep your details current so support feels personal.' : 'We keep your professional details organized and transparent.'}</p><form onSubmit={submit} className="auth-form">{renderStep()}{error && <p className="form-message" role="alert">{error}</p>}<button className="primary-button" type="submit" disabled={busy}>{busy ? 'Creating account...' : step === steps.length ? (customer ? 'Create Account' : 'Submit for Verification') : 'Continue'} {!busy && <ArrowRight size={17} />}</button></form><p className="login-hint">Already have an account? <Link to="/login">Login</Link></p></section></main></Shell>
}

function Review({ label, value }: { label: string; value: string | undefined }) { return <div className="review-item"><span>{label}</span><strong>{value || 'Not provided'}</strong></div> }

function StatusPage() { const navigate = useNavigate(); const technician = window.location.pathname.includes('technician') || window.location.pathname.includes('electrician'); return <Shell><main className="status-layout"><section className="status-card"><div className="success-mark"><Check size={28} /></div><div className="eyebrow">{technician ? 'APPLICATION CREATED' : 'ACCOUNT READY'}</div><h1>{technician ? 'Your technician application is created.' : 'Account created successfully.'}</h1><p>{technician ? 'Your profile is ready for the next review stage. You can continue to the technician dashboard while your application is processed.' : 'Welcome to SmartAssist AI. Your account is ready to help you get more from your home.'}</p>{technician ? <div className="timeline">{['Account created', 'Professional details added', 'Service area added', 'Application submitted'].map((item) => <div className="timeline-item complete" key={item}><span><Check size={14} /></span>{item}</div>)}</div> : <div className="notice"><ShieldCheck size={18} /> You can add devices later from your dashboard.</div>}<button className="primary-button" type="button" onClick={() => navigate(technician ? '/technician/dashboard' : '/customer/dashboard')}>{technician ? 'Go to Technician Dashboard' : 'Go to Customer Dashboard'} <ArrowRight size={17} /></button></section></main></Shell> }

function UtilityPage({ reset = false }: { reset?: boolean }) { return <Shell back><main className="status-layout"><section className="status-card"><div className="role-icon"><LockKeyhole size={21} /></div><h1>{reset ? 'Create a new password' : 'Forgot password?'}</h1><p>{reset ? 'Choose a new password for your SmartAssist account.' : "Enter your registered email or mobile number. If an account exists, we'll send reset instructions."}</p><form className="auth-form" onSubmit={(event) => event.preventDefault()}>{!reset && <Field label="Email or Mobile Number" value="" onChange={() => undefined} placeholder="you@example.com" />}{reset && <><Field label="New Password" value="" onChange={() => undefined} placeholder="At least 8 characters" /><Field label="Confirm Password" value="" onChange={() => undefined} placeholder="Repeat your password" /></>}<button className="primary-button" type="submit">{reset ? 'Reset Password' : 'Send Reset Code'} <ArrowRight size={17} /></button></form><Link className="center-link" to="/login">Return to login</Link></section></main></Shell> }

function DashboardPlaceholder() { const location = useLocation(); const technician = location.pathname.includes('technician') || location.pathname.includes('electrician'); return <Shell><main className="status-layout"><section className="status-card"><div className="role-icon"><Sparkles size={21} /></div><h1>{technician ? 'Technician dashboard ready' : 'Dashboard access ready'}</h1><p>This authentication destination is wired for the next project phase. Protected dashboard screens remain intentionally outside this portal.</p><Link className="secondary-button" to="/login">Return to login</Link></section></main></Shell> }

export default App
